version: '3.8'

services:
  db:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_DB: rbac_assignment
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    volumes:
      - pg_data:/var/lib/postgresql/data
    # ports:
    #   - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    ports:
      - "8000:8000"
    restart: always
    environment:
      DATABASE_URL: postgresql://postgres:123456@db:5432/rbac_assignment
      SECRET_KEY: supersecret
      REFRESH_SECRET_KEY: supersecret_refresh
      ALGORITHM: HS256
      ACCESS_EXPIRE_MIN: 15
      REFRESH_EXPIRE_MIN: 1440
    depends_on:
      db:
        condition: service_healthy
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

volumes:
  pg_data:
